In [72]:
import pandas as pd
from sklearn import tree
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [73]:
# define cols to load
part = 100000
desired_cols = ['DateOfCall', 'StopCodeDescription', 'PropertyType', 
                'FirstPumpArriving_AttendanceTime']

# load dataset, remove NaN
# ds = pd.read_csv('data/lfb_incident.csv', usecols=desired_cols)
ds = pd.read_csv('out.csv', usecols=desired_cols)
ds = ds.dropna()
ds = ds[0:part]

X = ds.drop('FirstPumpArriving_AttendanceTime', axis=1)
y = ds[['FirstPumpArriving_AttendanceTime']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [74]:
#ds["DateOfCall"] = ds["DateOfCall"].apply(lambda x: datetime.strptime(x, '%d %b %Y').strftime('%Y-%m-%d'))
#for col in desired_cols:
#    unique_date = ds[col].unique()
#    for date in unique_date:
#        ds[col] = ds[col].replace(date, np.where(unique_date == date)[0][0])
#ds[1:50]
#ds.to_csv('out.csv', index=False)

In [75]:
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)

DecisionTreeClassifier()

In [76]:
#plt.figure(figsize=(120,40))
#tree.plot_tree(clf, fontsize=15, feature_names=['DateOfCall', 'StopCodeDescription', 'PropertyType']);
#plt.savefig('test.pdf')  

In [77]:
pred = clf.predict(X_test)
pred

array([ 34., 110., 464., ...,  67., 367.,  67.])

In [78]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

         0.0       0.01      0.03      0.01       102
         1.0       0.00      0.01      0.00       101
         2.0       0.00      0.02      0.01       110
         3.0       0.00      0.02      0.01       117
         4.0       0.01      0.02      0.01        85
         5.0       0.00      0.00      0.00        46
         6.0       0.00      0.02      0.01       179
         7.0       0.00      0.00      0.00       179
         8.0       0.00      0.00      0.00       139
         9.0       0.00      0.01      0.00       133
        10.0       0.00      0.00      0.00        21
        11.0       0.00      0.00      0.00        15
        12.0       0.00      0.00      0.00       137
        13.0       0.00      0.00      0.00        17
        14.0       0.00      0.00      0.00        16
        15.0       0.01      0.02      0.01       136
        16.0       0.00      0.00      0.00        33
        17.0       0.01    

/home/ullmann/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ullmann/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ullmann/.local/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ullmann/.local/lib/python3.8/site-packa

In [79]:
print(confusion_matrix(y_test, y_pred))

[[3 2 2 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [0 2 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
